# Generated by Django 4.2.30 on 2026-10-04 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('WORKER', 'Worker / Labour'), ('EMPLOYER', 'Job Provider / Employer'), ('ADMIN', 'Administrator')], default='WORKER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='workers/')),
                ('skills', models.JSONField(default=list, help_text="List of skills e.g., ['Electrician', 'Plumber']")),
                ('location', models.CharField(default='New Delhi, India', max_length=255)),
                ('latitude', models.FloatField(default=28.6139)),
                ('longitude', models.FloatField(default=77.209)),
                ('experience_years', models.IntegerField(default=1)),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Available for Work'), ('BUSY', 'Currently Working'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20)),
                ('rating', models.FloatField(default=5.0)),
                ('total_ratings_count', models.IntegerField(default=0)),
                ('completed_jobs_count', models.IntegerField(default=0)),
                ('about', models.TextField(blank=True, default='Experienced daily-wage worker looking for reliable local work.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='employers/')),
                ('company_name', models.CharField(blank=True, default='', max_length=150)),
                ('is_individual', models.BooleanField(default=True)),
                ('location', models.CharField(default='New Delhi, India', max_length=255)),
                ('latitude', models.FloatField(default=28.6139)),
                ('longitude', models.FloatField(default=77.209)),
                ('about', models.TextField(blank=True, default='Verified employer posting short-term daily wage jobs.')),
                ('rating', models.FloatField(default=5.0)),
                ('total_ratings_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
