# Generated by Django 4.2.30 on 2026-10-04 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Job Creation'), ('HELD', 'Escrow Held / Locked'), ('RELEASED', 'Payment Released to Worker'), ('CANCELLED', 'Escrow Cancelled / Refunded')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, default='Simulated Escrow Payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_payment', to='jobs.job')),
            ],
        ),
    ]
